### PR TITLE
Check for end of string properly when length given

### PR DESCRIPTION
**Pull request by charmander**
Addresses #16.

### CODE REVIEW

**Comment by Ed-von-Schleck** [comment]
Thanks! It was a while that I looked at that code, but I take it from you that it's correct now.

**Comment by charmander** [comment]
@Ed-von-Schleck, did you merge this…?

**Comment by Ed-von-Schleck** [comment]
I think I did ... let me re-open and check (was in a hurry)

**Comment by Ed-von-Schleck** [comment]
Oh, I needed to confim! Sorry about that!

**Pull request merged**
